# fly.toml - API

app = 'numina-api'

[build]
  dockerfile = "Dockerfile"

[env]

[processes]
app = "uvicorn app.main:app --host 0.0.0.0 --port 8080"

[http_service]
internal_port = 8080
processes = ["app"]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
