"""add astrology_blueprint to user

Revision ID: b3bb49408c6c
Revises: 1c54843cf28f
Create Date: 2026-03-11 21:23:29.924180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3bb49408c6c'
down_revision: Union[str, None] = '1c54843cf28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('astrology_blueprint', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'astrology_blueprint')
    # ### end Alembic commands ###
