"""convert cosmic_traits_summary to jsonb

Revision ID: e4259d399410
Revises: 3db9bb291072
Create Date: 2026-04-19 22:30:26.507722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4259d399410'
down_revision: Union[str, None] = '3db9bb291072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Clear existing plain text data to avoid JSONB conversion errors
    op.execute("UPDATE users SET cosmic_traits_summary = NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cosmic_traits_summary',
               existing_type=sa.VARCHAR(length=1000),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using="cosmic_traits_summary::jsonb")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cosmic_traits_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###
