"""add_soul_snapshot

Revision ID: 4aa8bcf74aee
Revises: 5ec54feebbe4
Create Date: 2026-04-19 20:25:47.984960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4aa8bcf74aee'
down_revision: Union[str, None] = '5ec54feebbe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('soul_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('users', 'daily_message_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_message_cache', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('users', 'soul_snapshot')
    # ### end Alembic commands ###
