"""add blueprint fields to user

Revision ID: 1c54843cf28f
Revises: 013
Create Date: 2026-03-11 14:03:02.289211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c54843cf28f'
down_revision: Union[str, None] = '013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_constraint(op.f('uq_user_synthesis_user_type'), 'user_synthesis', type_='unique')
    op.add_column('users', sa.Column('sun_sign', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('sun_description', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('moon_sign', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('moon_description', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('rising_sign', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('rising_description', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('cosmic_traits_summary', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('numerology_blueprint', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'numerology_blueprint')
    op.drop_column('users', 'cosmic_traits_summary')
    op.drop_column('users', 'rising_description')
    op.drop_column('users', 'rising_sign')
    op.drop_column('users', 'moon_description')
    op.drop_column('users', 'moon_sign')
    op.drop_column('users', 'sun_description')
    op.drop_column('users', 'sun_sign')
    op.create_unique_constraint(op.f('uq_user_synthesis_user_type'), 'user_synthesis', ['user_id', 'synthesis_type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    # ### end Alembic commands ###
