"""Add birthday_number to users table

Revision ID: 4fc1f7c9f584
Revises: b3bb49408c6c
Create Date: 2026-04-02 09:47:09.977248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc1f7c9f584'
down_revision: Union[str, None] = 'b3bb49408c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthday_number')
    # ### end Alembic commands ###
