GATE_PRIORITY = [
    "sun",
    "earth",
    "moon",
    "mercury",
    "mars",
    "node",
    "venus",
    "saturn",
    "jupiter",
    "uranus",
    "neptune",
    "pluto"
]

GATE_MEANING_MAP = {
    1: "expresses creativity in a unique and individual way",
    2: "senses natural direction and responds to where life is leading",
    4: "seeks logical answers and mental solutions",
    5: "prefers consistent routines and natural timing",
    6: "manages emotional boundaries in relationships",
    7: "guides direction within groups and shared paths",
    9: "focuses deeply on small details and sustained attention",
    10: "acts according to an inner sense of self",
    11: "generates many ideas and mental possibilities",
    12: "expresses emotions carefully and selectively",
    13: "listens deeply and absorbs other people's stories",
    14: "generates and manages resources effectively",
    17: "forms structured opinions about how things work",
    18: "notices what can be improved or corrected",
    20: "acts in the present moment and responds quickly",
    22: "expresses emotions according to mood and receptivity",
    24: "revisits ideas repeatedly until clarity is found",
    28: "seeks purpose through challenge, risk, and meaning",
    31: "influences others through voice and leadership",
    33: "reflects on past experiences before speaking",
    34: "acts with strong, independent energy",
    35: "seeks new experiences and change through action",
    36: "learns through emotional intensity and uncertainty",
    37: "seeks emotional security and loyalty in close relationships",
    38: "struggles to find meaningful purpose and worthy effort",
    41: "initiates new emotional experiences and desires",
    42: "completes cycles and learns through experience",
    45: "speaks with authority around resources, direction, or stewardship",
    47: "turns confusion into insight over time",
    48: "seeks depth and mastery before acting",
    49: "reacts strongly to values, fairness, and emotional principles",
    52: "stays still to maintain focus and concentration",
    53: "starts new cycles and initiatives",
    56: "communicates through stories, examples, and lived experience",
    57: "reacts quickly based on intuitive awareness",
    62: "focuses on details, naming, and precision"
}
