GATE_PRIORITY = [
    "sun",
    "earth",
    "moon",
    "mercury",
    "mars",
    "node",
    "venus",
    "saturn",
    "jupiter",
    "uranus",
    "neptune",
    "pluto"
]

GATE_MEANING_MAP = {
    1: "tends to express creativity in an individual way",
    2: "intuitively senses direction and flow in life",
    4: "tends to seek logical answers and mental solutions",
    5: "naturally prefers consistent timing and routine",
    6: "tends to manage emotional boundaries in relationships",
    7: "naturally guides collective direction",
    9: "tends to focus deeply on small detailed tasks",
    10: "naturally acts from inner self-identity",
    11: "tends to generate diverse mental ideas",
    12: "naturally expresses emotions with caution",
    13: "tends to listen deeply to others’ experiences",
    14: "naturally manages and generates resources",
    17: "tends to form structured logical opinions",
    18: "naturally identifies areas for improvement",
    20: "tends to act quickly in the present moment",
    22: "naturally expresses emotions based on mood",
    24: "tends to revisit ideas for mental clarity",
    28: "naturally seeks purpose through challenges",
    31: "tends to lead others through influence",
    33: "naturally reflects on past experiences before moving forward",
    34: "tends to act with strong independent power",
    35: "naturally seeks change through experience",
    36: "tends to learn through emotional challenges",
    37: "naturally seeks emotional security and support",
    38: "tends to struggle for meaningful purpose",
    41: "naturally initiates new emotional experiences",
    42: "tends to complete cycles through growth",
    45: "naturally expresses authority over resources",
    47: "tends to transform confusion into insight",
    48: "naturally seeks depth and mastery",
    49: "tends to react strongly to values and principles",
    52: "naturally maintains focus through stillness",
    53: "tends to initiate new life cycles",
    56: "naturally communicates through storytelling",
    57: "tends to act on intuitive awareness",
    62: "naturally focuses on detailed precision"
}