"""Questions per test (frontend-aligned prompts and answer types). Test-specific result schemas live elsewhere."""

from app.schemas.test_result import QuestionOut, ShowWhen

CHAKRA_ALIGNMENT_SCAN_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="Rate your current overall energy level:",
        answer_type="slider",
        options=None,
        slider_min=0,
        slider_max=100,
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Which color feels most aligned with how you feel right now?",
        answer_type="color",
        options=["Red", "Orange", "Yellow", "Green", "Blue", "Indigo", "Violet", "White"],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="Where in your body do you most often notice tension or discomfort?",
        answer_type="single_choice",
        options=["Root", "Sacral", "Solar Plexus", "Heart", "Throat", "Third Eye", "Crown"],
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="Which emotion do you experience most strongly today?",
        answer_type="multiple_choice",
        options=[
            "Security/Anxiety",
            "Creativity/Pleasure",
            "Confidence/Self-Doubt",
            "Love/Vulnerability",
            "Communication/Blocks",
            "Clarity/Confusion",
            "Spiritual Connection/Escapism",
        ],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="Select any physical symptoms you've noticed recently:",
        answer_type="multiple_choice",
        options=[
            "Digestive Issues",
            "Neck/Throat Tightness",
            "Headaches",
            "Lower-Back Pain",
            "Chest Tightness",
            "Fatigue",
            "Over-thinking",
        ],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="How strong is your sense of purpose or connection to the Divine?",
        answer_type="single_choice",
        options=["Very Strong", "Moderate", "Weak", "Uncertain"],
        required=True,
    ),
    QuestionOut(
        id=7,
        prompt="Do you have any regular grounding or energy-clearing practices?",
        answer_type="single_choice",
        options=["Yes", "No"],
        required=True,
    ),
    QuestionOut(
        id=8,
        prompt="When under stress, what's your instinctive response?",
        answer_type="single_choice",
        options=["Fight", "Flight", "Freeze", "Flow"],
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt="How easy is it for you to speak your truth?",
        answer_type="single_choice",
        options=["Very Easy", "Sometimes Easy", "Often Difficult", "I Stay Silent"],
        required=True,
    ),
    QuestionOut(
        id=10,
        prompt='Do you experience vivid intuition, dreams, or sudden "downloads"?',
        answer_type="single_choice",
        options=["Frequently", "Occasionally", "Rarely", "Never"],
        required=True,
    ),
]

MBTI_TYPE_QUESTIONS: list[QuestionOut] = [
    # --- I / E ---
    QuestionOut(
        id=1,
        prompt="Where do you usually regain energy?",
        answer_type="single_choice",
        options=[
            "Spending quiet time alone (I)",
            "Being around people or social activity (E)",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="In social situations you tend to:",
        answer_type="single_choice",
        options=[
            "Listen more and speak selectively (I)",
            "Speak easily and engage actively (E)",
        ],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="After a busy day you prefer to:",
        answer_type="single_choice",
        options=[
            "Recharge in solitude (I)",
            "Do something with others (E)",
        ],
        required=True,
    ),
    # --- N / S ---
    QuestionOut(
        id=4,
        prompt="When learning something new you prefer:",
        answer_type="single_choice",
        options=[
            "Concepts and possibilities (N)",
            "Practical details and facts (S)",
        ],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="When thinking about the future you focus more on:",
        answer_type="single_choice",
        options=[
            "What could be possible (N)",
            "What is realistically likely (S)",
        ],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="You tend to trust more:",
        answer_type="single_choice",
        options=[
            "Patterns and intuition (N)",
            "Experience and observable facts (S)",
        ],
        required=True,
    ),
    # --- F / T ---
    QuestionOut(
        id=7,
        prompt="When making decisions you usually rely more on:",
        answer_type="single_choice",
        options=[
            "Personal values and empathy (F)",
            "Logic and objective analysis (T)",
        ],
        required=True,
    ),
    QuestionOut(
        id=8,
        prompt="In conflict situations you prioritize:",
        answer_type="single_choice",
        options=[
            "Maintaining harmony (F)",
            "Finding the most rational solution (T)",
        ],
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt="You tend to evaluate situations based on:",
        answer_type="single_choice",
        options=[
            "How people are affected (F)",
            "What makes the most sense logically (T)",
        ],
        required=True,
    ),
    # --- J / P ---
    QuestionOut(
        id=10,
        prompt="You generally prefer your life to feel:",
        answer_type="single_choice",
        options=[
            "Organized and planned (J)",
            "Flexible and spontaneous (P)",
        ],
        required=True,
    ),
    QuestionOut(
        id=11,
        prompt="When approaching tasks you usually:",
        answer_type="single_choice",
        options=[
            "Plan ahead and follow structure (J)",
            "Adapt as things unfold (P)",
        ],
        required=True,
    ),
    QuestionOut(
        id=12,
        prompt="You feel most comfortable when:",
        answer_type="single_choice",
        options=[
            "Decisions are settled (J)",
            "Options remain open (P)",
        ],
        required=True,
    ),
]

STARSEED_ORIGINS_QUESTIONS: list[QuestionOut] = [
    # Part A — Social Role
    QuestionOut(
        id=1,
        prompt="How do you typically relate to others?",
        answer_type="single_choice",
        options=[
            "I’m a natural helper but often wait to be asked",
            "I prefer observing until I feel called in",
            "I leap in to lead or guide immediately",
            "I stay in the background and offer support quietly",
        ],
        required=True,
    ),
    # Part B — Curiosity
    QuestionOut(
        id=2,
        prompt="Which topics spark your deepest curiosity? (Select up to 3)",
        answer_type="multiple_choice",
        options=[
            "Space, stars, extraterrestrial life",
            "Ancient wisdom and civilizations",
            "Cutting-edge science and technology",
            "Mystical or spiritual practices",
            "Environmental harmony and nature",
            "Energy healing and consciousness",
        ],
        max_selections=3,
        required=True,
    ),
    # Part C — Nature Resonance
    QuestionOut(
        id=3,
        prompt="When you’re in nature, what resonates most?",
        answer_type="single_choice",
        options=[
            "The calm grounding earth beneath my feet",
            "The flow of water or breeze",
            "The vast sky and stars above",
            "The intricate details of plants and life",
        ],
        required=True,
    ),
    # Part D — Mission
    QuestionOut(
        id=4,
        prompt="How would you describe your sense of calling?",
        answer_type="single_choice",
        options=[
            "To heal and comfort others",
            "To build or innovate new systems",
            "To teach and share wisdom",
            "To protect nature and life",
        ],
        required=True,
    ),
    # Part E — Social Energy
    QuestionOut(
        id=5,
        prompt="At a gathering you feel most yourself when:",
        answer_type="single_choice",
        options=[
            "In deep one-on-one conversations",
            "In small groups exploring ideas",
            "Speaking to or teaching the crowd",
            "Quietly observing from the edges",
        ],
        required=True,
    ),
    # Part F — Decision Style
    QuestionOut(
        id=6,
        prompt="When making big decisions you trust:",
        answer_type="single_choice",
        options=[
            "Emotional intuition",
            "Logical reasoning",
            "A balance of both",
        ],
        required=True,
    ),
    # Part G — Pace of Life
    QuestionOut(
        id=7,
        prompt="Which pace fits you best?",
        answer_type="single_choice",
        options=[
            "Steady and grounded",
            "Free-flowing and adaptable",
            "Structured and goal-oriented",
            "Calm and reflective",
        ],
        required=True,
    ),
    # Part H — Belief Orientation
    QuestionOut(
        id=8,
        prompt="I often feel drawn to cosmic or universal questions.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt="I feel a strong desire to help humanity evolve.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=10,
        prompt="I am curious about how consciousness works.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=11,
        prompt="Nature feels deeply restorative to me.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=12,
        prompt="I often feel like I see things differently than most people.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
]

SHADOW_WORK_LENS_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="I often feel guilty about expressing anger or frustration.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="There are creative urges I've been too afraid to explore.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="I sometimes judge myself harshly for my desires or impulses.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="I hold back part of myself to avoid conflict or rejection.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="I experience sudden mood shifts that surprise me.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="I keep certain talents or gifts hidden from others.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=7,
        prompt="I'm drawn to understanding my dreams, even if they unsettle me.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=8,
        prompt="When you experience an intense emotion, which do you most often do?",
        answer_type="single_choice",
        options=[
            "I lecture myself to \"just calm down.\"",
            "I push the feeling away and busy myself.",
            "I journal or express it creatively.",
            "I share it with someone I trust.",
        ],
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt="Which phrase best describes your relationship with your \"inner critic\"?",
        answer_type="single_choice",
        options=[
            "It keeps me safe but holds me back.",
            "It rarely speaks — I ignore my inner voice.",
            "It offers harsh feedback I try to shut out.",
            "It's a guide I'm learning to dialogue with.",
        ],
        required=True,
    ),
    QuestionOut(
        id=10,
        prompt="In your everyday routine, how often do you check in with difficult or \"shadow\" emotions?",
        answer_type="single_choice",
        options=["Never", "Occasionally", "Sometimes", "Often", "Daily"],
        required=True,
    ),
]

CORE_VALUES_OPTIONS = [
    "Depth", "Freedom", "Authenticity", "Compassion", "Innovation", "Stability",
    "Adventure", "Integrity", "Connection", "Growth", "Balance", "Courage",
]

CORE_VALUES_SORT_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="Which matters most to you in life?",
        answer_type="single_choice",
        options=[
            "Learning and growing as a person",
            "Building meaningful relationships",
            "Having independence and freedom",
            "Creating stability and safety",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="What gives you the greatest satisfaction?",
        answer_type="single_choice",
        options=[
            "Improving yourself or mastering something",
            "Feeling deeply connected to people",
            "Doing things your own way",
            "Building a secure and stable life",
        ],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="If forced to choose, which would you prioritize?",
        answer_type="single_choice",
        options=[
            "Personal growth",
            "Relationships",
            "Freedom",
            "Security",
        ],
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="Which situation feels most fulfilling?",
        answer_type="single_choice",
        options=[
            "Learning something that expands your mind",
            "Supporting or helping others",
            "Exploring new experiences",
            "Creating long-term stability",
        ],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="Personal growth is one of my highest priorities.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="Strong relationships give life its meaning.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=7,
        prompt="Freedom and independence are essential to me.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=8,
        prompt="Security and stability are very important to me.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt="I want to make a meaningful impact on the world.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=10,
        prompt="Creativity and self-expression matter deeply to me.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=11,
        prompt="I value harmony and emotional balance in my life.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=12,
        prompt="Achievement and success motivate me strongly.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
]

COGNITIVE_STYLE_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="A colleague seems upset but hasn't said why. You:",
        answer_type="single_choice",
        options=[
            "Analyze recent events to deduce the cause before approaching them.",
            "Gently ask, \"You seem off—want to talk about it?\"",
            "Offer a quick practical suggestion (\"Maybe take a break?\").",
            "Sit quietly with them until they're ready to share.",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="You're faced with a complex problem at work. You:",
        answer_type="single_choice",
        options=[
            "Break it into parts and tackle each logically.",
            "Check in with how you feel about each possible solution.",
            "Brainstorm creative ideas first, then evaluate feasibility.",
            "Ask team members for their emotional reactions and suggestions.",
        ],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="I trust my gut feelings as much as facts when making decisions.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="I enjoy digging into data to understand social dynamics.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="I feel compelled to consider others' emotions before choosing a course of action.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="When you must decide quickly, you rely on:",
        answer_type="single_choice",
        options=[
            "Logic & analysis",
            "Intuition & feeling",
            "A mix of both",
        ],
        required=True,
    ),
]

MIND_MIRROR_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="What thought or concern has been taking up the most space in your mind lately?",
        answer_type="text",
        options=None,
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Which of these best describes your emotional state recently?",
        answer_type="single_choice",
        options=["Calm", "Stressed", "Energized", "Drained", "Curious", "Emotionally overwhelmed"],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="What situation recently made you think deeply about yourself or your life?",
        answer_type="text",
        options=None,
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="Which area has felt most out of balance for you recently?",
        answer_type="single_choice",
        options=[
            "Mind (overthinking / mental pressure)",
            "Heart (emotional overload / relationship tension)",
            "Body (fatigue / physical stress)",
            "Spirit (lack of meaning / inspiration)",
        ],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="What is one change, intention, or mindset shift that would help you feel more balanced?",
        answer_type="text",
        options=None,
        required=True,
    ),
]

ENERGY_ARCHETYPE_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="My ideas usually begin as emotional or intuitive sparks.",
        answer_type="single_choice",
        options=[
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="I feel best when I can organize thoughts into a clear structure.",
        answer_type="single_choice",
        options=[
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree",
        ],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="My best decisions happen when logic and feeling work together.",
        answer_type="single_choice",
        options=[
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree",
        ],
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="I sometimes feel my emotions move faster than my reasoning.",
        answer_type="single_choice",
        options=[
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree",
        ],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="I tend to overthink emotions instead of simply feeling them.",
        answer_type="single_choice",
        options=[
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree",
        ],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="I enjoy exploring possibilities more than following strict plans.",
        answer_type="single_choice",
        options=[
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree",
        ],
        required=True,
    ),
     QuestionOut(
        id=7,
        prompt="I trust analysis more than instinct when making important decisions.",
        answer_type="single_choice",
        options=[
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree",
        ],
        required=True,
    ),
     QuestionOut(
        id=8,
        prompt="I feel most energized when I can turn inspiration into action.",
        answer_type="single_choice",
        options=[
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree",
        ],
        required=True,
    ),
     QuestionOut(
        id=9,
        prompt="I prefer balance between planning and creative freedom.",
        answer_type="single_choice",
        options=[
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree",
        ],
        required=True,
    ),
     QuestionOut(
        id=10,
        prompt="I often feel mentally overloaded when emotions and thoughts conflict.",
        answer_type="single_choice",
        options=[
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree",
        ],
        required=True,
    ),
    QuestionOut(
        id=11,
        prompt="I can usually step back and integrate feeling with perspective.",
        answer_type="single_choice",
        options=[
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree",
        ],
        required=True,
    ),
    QuestionOut(
        id=12,
        prompt="I feel either too emotionally reactive or too mentally detached when stressed.",
        answer_type="single_choice",
        options=[
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree",
        ],
        required=True,
    ),
]

EMOTIONAL_REGULATION_TYPE_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="I often keep my emotions inside until I have space to process them alone.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="When I feel strong emotions, I prefer to talk about them with someone I trust.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="I tend to analyze why I feel something rather than simply experiencing it.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="When emotions build up, I eventually need to release them physically or verbally.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="I can usually stay calm even when strong emotions arise.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="I often distract myself with work, media, or tasks instead of feeling emotions directly.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=7,
        prompt="I feel comfortable expressing emotions in the moment.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=8,
        prompt="Sometimes emotions stay inside me longer than I would like.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt="I try to understand the meaning behind my emotional reactions.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=10,
        prompt="When emotions become overwhelming, I need an outlet.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=11,
        prompt="I can step back and regulate my emotional state when needed.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=12,
        prompt="I sometimes feel emotions suddenly erupt after holding them in.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
]

STRESS_BALANCE_INDEX_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="What usually appears first when stress builds?",
        answer_type="single_choice",
        options=["Tight shoulders or neck", "Racing thoughts", "Irritability with others", "Forgetfulness or mental fog"],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="When stress becomes intense, you usually:",
        answer_type="single_choice",
        options=["Power through until exhausted", "Take a short break and reset", "Have an emotional release", "Feel numb or shut down"],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="How quickly do you notice you need a break?",
        answer_type="single_choice",
        options=["Immediately", "After ~30 minutes", "After ~1 hour", "Only when completely exhausted"],
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="I can usually detect stress signals in my body early.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="I tend to ignore stress until it becomes overwhelming.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="I can pause and regulate myself when pressure rises.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=7,
        prompt="I often continue pushing myself even when tired.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=8,
        prompt="Emotional tension sometimes builds until it releases suddenly.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt="Taking breaks helps me regain mental clarity.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=10,
        prompt="Stress sometimes causes me to mentally shut down.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=11,
        prompt="I can usually step back before reaching burnout.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=12,
        prompt="I notice physical stress signals before emotional ones.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
]

SOMATIC_CONNECTION_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="Where do you first feel stress or emotion physically?",
        answer_type="single_choice",
        options=["Chest", "Belly", "Shoulders", "Head", "I rarely notice physical signals"],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Which body-based practice do you use regularly?",
        answer_type="single_choice",
        options=["Breathwork", "Yoga or stretching", "Movement (dance, exercise)", "Massage or bodywork", "None"],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="I notice physical tension before it becomes painful.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="I can usually identify where emotions appear in my body.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="Stress often shows up as tightness or pressure somewhere in my body.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="I sometimes ignore physical signals until they become overwhelming.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=7,
        prompt="Movement helps me process emotions.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=8,
        prompt="I feel emotionally lighter after releasing tension physically.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt="I feel disconnected from my body during stress.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=10,
        prompt="I can consciously relax my body when tension builds.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=11,
        prompt="Emotional experiences often leave physical sensations in my body.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=12,
        prompt="I can use breathing or grounding to calm physical stress.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
]

ENERGY_SYNTHESIS_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="When problem-solving, you prefer:",
        answer_type="single_choice",
        options=[
            "Emotion → Analysis → Action",
            "Analysis → Emotion → Action",
            "Emotion + Analysis simultaneously",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Do you schedule set times for 'feeling-only' and 'thinking-only'?",
        answer_type="single_choice",
        options=["Yes", "No"],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="Rate: I experience breakthroughs when I alternate feeling and thinking. (1 = Strongly Disagree, 5 = Strongly Agree)",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="Rate: My decisions improve when I balance heart and mind. (1 = Strongly Disagree, 5 = Strongly Agree)",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="Rate: I tend to favor one over the other, causing imbalance. (1 = Strongly Disagree, 5 = Strongly Agree)",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
]

PAST_LIFE_VIBES_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="When guiding or teaching others, what feels most natural?",
        answer_type="single_choice",
        options=[
            "Instant familiarity and ease",
            "Nervous anticipation that fades quickly",
            "Curiosity about why it feels right",
            "Neutral, like any other task",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Which activities feel like “second nature”? (Select up to 2)",
        answer_type="multiple_choice",
        options=[
            "Storytelling or mentoring",
            "Research or studying ancient knowledge",
            "Protecting or defending others",
            "Meditation or spiritual practice",
            "Exploring new places or cultures",
            "Building or organizing systems",
        ],
        max_selections=2,
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="I feel drawn to ancient knowledge or wisdom traditions.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="Helping others heal emotionally or physically feels natural.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="I feel energized when protecting or standing up for others.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="I often feel connected to spiritual or mystical experiences.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=7,
        prompt="Exploring unknown places or ideas excites me.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=8,
        prompt="I enjoy organizing systems or building practical structures.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt="I sometimes feel strong familiarity with certain historical eras.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=10,
        prompt="I feel a sense of purpose when sharing knowledge.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=11,
        prompt="I trust intuition or spiritual insight when making decisions.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=12,
        prompt="I often feel pulled toward discovering new frontiers.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
]

KARMIC_LESSONS_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="Which pattern shows up most often in your life?",
        answer_type="single_choice",
        options=[
            "I give too much and feel drained",
            "I struggle to say what I really feel",
            "I find it hard to trust others fully",
            "I doubt my value or deserve less",
            "I try to control outcomes too much",
            "I get frustrated when life moves slowly",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="When conflict appears, I usually:",
        answer_type="single_choice",
        options=[
            "over-give or over-accommodate",
            "stay quiet until it builds up",
            "become suspicious or guarded",
            "blame myself",
            "try to manage everything",
            "feel irritated by delays",
        ],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="I often struggle to protect my own energy and limits.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="I find it difficult to express my truth clearly.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="Trusting people deeply takes me a long time.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="I sometimes feel I must earn love, care, or belonging.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=7,
        prompt="I feel uneasy when I am not in control of outcomes.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=8,
        prompt="Waiting for things to unfold naturally is hard for me.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt="I repeat similar lessons in relationships again and again.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=10,
        prompt="I often notice the same emotional challenge returning in different forms.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=11,
        prompt="I feel there is one life lesson I am meant to grow through.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=12,
        prompt="I want to break old patterns and respond differently.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
]

INNER_CHILD_DIALOGUE_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="When you feel anxious or sad, you usually:",
        answer_type="single_choice",
        options=[
            "Comfort yourself with kind words",
            "Distract yourself until it passes",
            "Criticize yourself (“snap out of it”)",
            "Seek support from someone else",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Do you remember unresolved childhood hurts?",
        answer_type="single_choice",
        options=["Yes", "No", "Unsure"],
        required=True,
    ),
    QuestionOut(
        id=13,
        prompt="List one or two (optional):",
        answer_type="text",
        options=None,
        show_when=ShowWhen(question_id=2, value="Yes"),
        required=False,
    ),
    QuestionOut(
        id=3,
        prompt="I try to comfort myself when I feel emotionally overwhelmed.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="I often distract myself instead of sitting with difficult feelings.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="I sometimes judge myself harshly when I struggle.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="I feel safe asking others for emotional support.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=7,
        prompt="I can recognize when my inner child feels hurt or scared.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=8,
        prompt="I try to treat myself with compassion when emotions arise.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt="I often push feelings away instead of acknowledging them.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=10,
        prompt="I can speak kindly to myself when I make mistakes.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=11,
        prompt="I notice old childhood patterns appearing in adult relationships.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
    QuestionOut(
        id=12,
        prompt="I actively work on healing emotional wounds.",
        answer_type="single_choice",
        options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
        required=True,
    ),
]

BIG_FIVE_QUESTIONS: list[QuestionOut] = [
    # Openness
    QuestionOut(id=1, prompt="I enjoy exploring new ideas.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=2, prompt="I like art, creativity, or imagination.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=3, prompt="I enjoy trying unfamiliar experiences.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=4, prompt="I enjoy philosophical discussions.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    # Conscientiousness
    QuestionOut(id=5, prompt="I keep my work organized.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=6, prompt="I follow through on commitments.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=7, prompt="I like planning ahead.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=8, prompt="I work carefully and avoid mistakes.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    # Extraversion
    QuestionOut(id=9, prompt="I feel energized by social interaction.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=10, prompt="I enjoy being the center of attention.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=11, prompt="I like meeting new people.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=12, prompt="I feel comfortable leading conversations.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    # Agreeableness
    QuestionOut(id=13, prompt="I try to understand others’ feelings.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=14, prompt="I enjoy helping people.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=15, prompt="I value cooperation over competition.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=16, prompt="I avoid unnecessary conflict.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    # Neuroticism
    QuestionOut(id=17, prompt="I often worry about things.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=18, prompt="I experience emotional ups and downs.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=19, prompt="I feel stressed easily.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
    QuestionOut(id=20, prompt="I sometimes overthink situations.", answer_type="single_choice", options=["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"], required=True),
]

SOUL_COMPASS_QUESTIONS: list[QuestionOut] = [
    QuestionOut(id=0, prompt="What is the important life decision you are evaluating?", answer_type="text", required=True),
    QuestionOut(id=1, prompt="Mind (Clarity)", answer_type="slider", required=True, slider_min=0, slider_max=100),
    QuestionOut(id=2, prompt="Heart (Emotion)", answer_type="slider", required=True, slider_min=0, slider_max=100),
    QuestionOut(id=3, prompt="Body (Grounding)", answer_type="slider", required=True, slider_min=0, slider_max=100),
    QuestionOut(id=4, prompt="Soul (Purpose)", answer_type="slider", required=True, slider_min=0, slider_max=100),
]

QUESTIONS_BY_TEST_ID: dict[int, list[QuestionOut]] = {
    3: STARSEED_ORIGINS_QUESTIONS,
    7: MBTI_TYPE_QUESTIONS,
    8: SHADOW_WORK_LENS_QUESTIONS,
    9: BIG_FIVE_QUESTIONS,
    10: CORE_VALUES_SORT_QUESTIONS,
    11: COGNITIVE_STYLE_QUESTIONS,
    12: MIND_MIRROR_QUESTIONS,
    13: CHAKRA_ALIGNMENT_SCAN_QUESTIONS,
    14: ENERGY_ARCHETYPE_QUESTIONS,
    15: EMOTIONAL_REGULATION_TYPE_QUESTIONS,
    16: STRESS_BALANCE_INDEX_QUESTIONS,
    17: SOMATIC_CONNECTION_QUESTIONS,
    18: ENERGY_SYNTHESIS_QUESTIONS,
    21: PAST_LIFE_VIBES_QUESTIONS,
    22: KARMIC_LESSONS_QUESTIONS,
    23: INNER_CHILD_DIALOGUE_QUESTIONS,
    24: SOUL_COMPASS_QUESTIONS,
}
