"""Questions per test (frontend-aligned prompts and answer types). Test-specific result schemas live elsewhere."""

from app.schemas.test_result import QuestionOut, ShowWhen

CHAKRA_ALIGNMENT_SCAN_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="Rate your current overall energy level:",
        answer_type="slider",
        options=None,
        slider_min=0,
        slider_max=100,
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Which color feels most aligned with how you feel right now?",
        answer_type="color",
        options=["Red", "Orange", "Yellow", "Green", "Blue", "Indigo", "Violet", "White"],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="Where in your body do you most often notice tension or discomfort?",
        answer_type="single_choice",
        options=["Root", "Sacral", "Solar Plexus", "Heart", "Throat", "Third Eye", "Crown"],
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="Which emotion do you experience most strongly today?",
        answer_type="multiple_choice",
        options=[
            "Security/Anxiety",
            "Creativity/Pleasure",
            "Confidence/Self-Doubt",
            "Love/Vulnerability",
            "Communication/Blocks",
            "Clarity/Confusion",
            "Spiritual Connection/Escapism",
        ],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="Select any physical symptoms you've noticed recently:",
        answer_type="multiple_choice",
        options=[
            "Digestive Issues",
            "Neck/Throat Tightness",
            "Headaches",
            "Lower-Back Pain",
            "Chest Tightness",
            "Fatigue",
            "Over-thinking",
        ],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="How strong is your sense of purpose or connection to the Divine?",
        answer_type="single_choice",
        options=["Very Strong", "Moderate", "Weak", "Uncertain"],
        required=True,
    ),
    QuestionOut(
        id=7,
        prompt="Do you have any regular grounding or energy-clearing practices?",
        answer_type="single_choice",
        options=["Yes", "No"],
        required=True,
    ),
    QuestionOut(
        id=8,
        prompt="When under stress, what's your instinctive response?",
        answer_type="single_choice",
        options=["Fight", "Flight", "Freeze", "Flow"],
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt="How easy is it for you to speak your truth?",
        answer_type="single_choice",
        options=["Very Easy", "Sometimes Easy", "Often Difficult", "I Stay Silent"],
        required=True,
    ),
    QuestionOut(
        id=10,
        prompt='Do you experience vivid intuition, dreams, or sudden "downloads"?',
        answer_type="single_choice",
        options=["Frequently", "Occasionally", "Rarely", "Never"],
        required=True,
    ),
]

MBTI_TYPE_QUESTIONS: list[QuestionOut] = [
    # --- I / E ---
    QuestionOut(
        id=1,
        prompt="Where do you usually regain energy?",
        answer_type="single_choice",
        options=[
            "Spending quiet time alone (I)",
            "Being around people or social activity (E)",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="In social situations you tend to:",
        answer_type="single_choice",
        options=[
            "Listen more and speak selectively (I)",
            "Speak easily and engage actively (E)",
        ],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="After a busy day you prefer to:",
        answer_type="single_choice",
        options=[
            "Recharge in solitude (I)",
            "Do something with others (E)",
        ],
        required=True,
    ),
    # --- N / S ---
    QuestionOut(
        id=4,
        prompt="When learning something new you prefer:",
        answer_type="single_choice",
        options=[
            "Concepts and possibilities (N)",
            "Practical details and facts (S)",
        ],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="When thinking about the future you focus more on:",
        answer_type="single_choice",
        options=[
            "What could be possible (N)",
            "What is realistically likely (S)",
        ],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="You tend to trust more:",
        answer_type="single_choice",
        options=[
            "Patterns and intuition (N)",
            "Experience and observable facts (S)",
        ],
        required=True,
    ),
    # --- F / T ---
    QuestionOut(
        id=7,
        prompt="When making decisions you usually rely more on:",
        answer_type="single_choice",
        options=[
            "Personal values and empathy (F)",
            "Logic and objective analysis (T)",
        ],
        required=True,
    ),
    QuestionOut(
        id=8,
        prompt="In conflict situations you prioritize:",
        answer_type="single_choice",
        options=[
            "Maintaining harmony (F)",
            "Finding the most rational solution (T)",
        ],
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt="You tend to evaluate situations based on:",
        answer_type="single_choice",
        options=[
            "How people are affected (F)",
            "What makes the most sense logically (T)",
        ],
        required=True,
    ),
    # --- J / P ---
    QuestionOut(
        id=10,
        prompt="You generally prefer your life to feel:",
        answer_type="single_choice",
        options=[
            "Organized and planned (J)",
            "Flexible and spontaneous (P)",
        ],
        required=True,
    ),
    QuestionOut(
        id=11,
        prompt="When approaching tasks you usually:",
        answer_type="single_choice",
        options=[
            "Plan ahead and follow structure (J)",
            "Adapt as things unfold (P)",
        ],
        required=True,
    ),
    QuestionOut(
        id=12,
        prompt="You feel most comfortable when:",
        answer_type="single_choice",
        options=[
            "Decisions are settled (J)",
            "Options remain open (P)",
        ],
        required=True,
    ),
]

STARSEED_ORIGINS_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="How do you typically relate to others?",
        answer_type="single_choice",
        options=[
            "I'm a natural helper but often wait to be asked",
            "I prefer observing until I feel called in",
            "I leap in to lead or guide immediately",
            "I stay in the background and offer support quietly",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Which topics spark your deepest curiosity?",
        answer_type="multiple_choice",
        options=[
            "Space, stars, and extraterrestrial life",
            "Ancient wisdom & cultures",
            "Cutting-edge science & technology",
            "Mystical or spiritual practices",
            "Environmental harmony & nature",
            "Energy healing & consciousness",
        ],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="When you're in nature, what resonates most?",
        answer_type="single_choice",
        options=[
            "The calm, grounding earth beneath my feet",
            "The flow and freedom of water or breeze",
            "The vastness of sky and stars above",
            "The intricate details of plants and life",
        ],
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="How would you describe your sense of mission or calling?",
        answer_type="single_choice",
        options=[
            "To heal and comfort others",
            "To build or innovate new systems",
            "To teach and share wisdom",
            "To protect nature and life",
        ],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt='In a social gathering, where do you feel most "yourself"?',
        answer_type="single_choice",
        options=[
            "Deep one-on-one conversations",
            "Small groups exploring ideas",
            "Speaking to or teaching the crowd",
            "Quiet corners observing energy",
        ],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="When making a big decision, do you trust…",
        answer_type="single_choice",
        options=[
            'Your emotional "knowing" (heart)',
            "Your logical analysis (mind)",
            "A balance of gut feeling and facts",
        ],
        required=True,
    ),
    QuestionOut(
        id=7,
        prompt="Pick the phrase that best describes your preferred pace of life:",
        answer_type="single_choice",
        options=[
            "Steady and grounded",
            "Free-flowing and changeable",
            "Structured and goal-oriented",
        ],
        required=True,
    ),
]

SHADOW_WORK_LENS_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="I often feel guilty about expressing anger or frustration.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="There are creative urges I've been too afraid to explore.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="I sometimes judge myself harshly for my desires or impulses.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="I hold back part of myself to avoid conflict or rejection.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="I experience sudden mood shifts that surprise me.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="I keep certain talents or gifts hidden from others.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=7,
        prompt="Rate: I'm drawn to understanding my dreams, even if they unsettle me.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=8,
        prompt="When you experience an intense emotion, which do you most often do?",
        answer_type="single_choice",
        options=[
            'I lecture myself to "just calm down."',
            "I push the feeling away and busy myself.",
            "I journal or express it creatively.",
            "I share it with someone I trust.",
        ],
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt='Which phrase best describes your relationship with your "inner critic"?',
        answer_type="single_choice",
        options=[
            "It keeps me safe but holds me back.",
            "It rarely speaks—I ignore my inner voice.",
            "It offers harsh feedback I try to shut out.",
            "It's a guide I'm learning to dialogue with.",
        ],
        required=True,
    ),
    QuestionOut(
        id=10,
        prompt='In your everyday routine, how often do you check in with difficult or "shadow" emotions?',
        answer_type="single_choice",
        options=["Never", "Occasionally", "Sometimes", "Often", "Daily"],
        required=True,
    ),
]

CORE_VALUES_OPTIONS = [
    "Depth", "Freedom", "Authenticity", "Compassion", "Innovation", "Stability",
    "Adventure", "Integrity", "Connection", "Growth", "Balance", "Courage",
]

CORE_VALUES_SORT_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="Select your top 6 values.",
        answer_type="multiple_choice",
        options=CORE_VALUES_OPTIONS,
        max_selections=6,
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Of those 6, which single value is MOST essential to you?",
        answer_type="single_choice",
        options=None,
        options_from_question_id=1,
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="Of those 6, which single value is LEAST essential to you?",
        answer_type="single_choice",
        options=None,
        options_from_question_id=1,
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="Do any of your top values feel like they conflict?",
        answer_type="single_choice",
        options=["Yes", "No"],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="Which two values feel most in conflict?",
        answer_type="multiple_choice",
        options=None,
        options_from_question_id=1,
        show_when=ShowWhen(question_id=4, value="Yes"),
        max_selections=2,
        required=True,
    ),
]

COGNITIVE_STYLE_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="A colleague seems upset but hasn't said why. You:",
        answer_type="single_choice",
        options=[
            "Analyze recent events to deduce the cause before approaching them.",
            "Gently ask, \"You seem off—want to talk about it?\"",
            "Offer a quick practical suggestion (\"Maybe take a break?\").",
            "Sit quietly with them until they're ready to share.",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="You're faced with a complex problem at work. You:",
        answer_type="single_choice",
        options=[
            "Break it into parts and tackle each logically.",
            "Check in with how you feel about each possible solution.",
            "Brainstorm creative ideas first, then evaluate feasibility.",
            "Ask team members for their emotional reactions and suggestions.",
        ],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="I trust my gut feelings as much as facts when making decisions.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="I enjoy digging into data to understand social dynamics.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="I feel compelled to consider others' emotions before choosing a course of action.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="When you must decide quickly, you rely on:",
        answer_type="single_choice",
        options=[
            "Logic & analysis",
            "Intuition & feeling",
            "A mix of both",
        ],
        required=True,
    ),
]

MIND_MIRROR_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="What's top of mind right now?",
        answer_type="text",
        options=None,
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="How do you feel emotionally?",
        answer_type="single_choice",
        options=["Calm", "Stressed", "Energized", "Drained", "Curious"],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="What was the highlight or challenge of today?",
        answer_type="text",
        options=None,
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="Over the past week, which area felt most off-balance?",
        answer_type="single_choice",
        options=[
            "Mind (overthinking)",
            "Heart (emotional overload)",
            "Body (fatigue)",
            "Spirit (disconnected)",
        ],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="What one small focus would improve that area next week?",
        answer_type="text",
        options=None,
        required=True,
    ),
]

ENERGY_ARCHETYPE_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="Which phrase best describes how your thoughts and feelings interact?",
        answer_type="single_choice",
        options=[
            "I get creative sparks that I then need to organize logically.",
            "I analyze first, then wait for an emotional cue.",
            "Thinking and feeling flow together seamlessly.",
            "One often overwhelms the other.",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Over a 30-minute period, do you prefer to:",
        answer_type="single_choice",
        options=[
            "Spend 20 min brainstorming ideas, 10 min planning.",
            "Spend 10 min brainstorming ideas, 20 min planning.",
            "Maintain a 15/15 split between both.",
        ],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="My best ideas emerge when I balance feeling with logic.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="I struggle when my emotions run ahead of my analysis.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="I feel stuck when I over-analyze my feelings.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
]

EMOTIONAL_REGULATION_TYPE_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="How often do you experience sudden emotional surges?",
        answer_type="single_choice",
        options=["Rarely", "Occasionally", "Sometimes", "Often", "Always"],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="When overwhelmed, you most often:",
        answer_type="single_choice",
        options=[
            "Take a deep breath and carry on quietly.",
            "Talk it out with someone.",
            "Distract yourself (work, scrolling, chores).",
            "Physically release it (punch pillow, dance).",
        ],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="I can keep emotions under control until I'm alone.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="I sometimes explode after too much holding in.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="I find it hard to share raw emotions as they arise.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
]

STRESS_BALANCE_INDEX_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="Which of these happens before you realize you're stressed?",
        answer_type="single_choice",
        options=[
            "Tight shoulders or neck",
            "Racing thoughts",
            "Irritability with others",
            "Forgetfulness or mental fog",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="When push comes to shove, you:",
        answer_type="single_choice",
        options=[
            "Power through until collapse.",
            "Take a short break.",
            "Have a sudden emotional release.",
            "Feel numb or shut down.",
        ],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="How quickly do you notice you need a break?",
        answer_type="single_choice",
        options=[
            "Immediately",
            "After 30 min",
            "After 1 hr",
            "Only when exhausted",
        ],
        required=True,
    ),
]

SOMATIC_CONNECTION_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="Where do you first feel stress or emotion physically?",
        answer_type="single_choice",
        options=["Chest", "Belly", "Shoulders", "Head", "Other"],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Which regular body-based practice do you use?",
        answer_type="single_choice",
        options=["Breathwork", "Yoga", "Dance", "Massage", "None"],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="I am aware of physical tension before it becomes painful.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="I can often pinpoint emotions by where they sit in my body.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="I rarely notice body signals until they become severe.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
]

ENERGY_SYNTHESIS_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="When problem-solving, you prefer:",
        answer_type="single_choice",
        options=[
            "Emotion → Analysis → Action",
            "Analysis → Emotion → Action",
            "Emotion + Analysis simultaneously",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Do you schedule set times for 'feeling-only' and 'thinking-only'?",
        answer_type="single_choice",
        options=["Yes", "No"],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="Rate: I experience breakthroughs when I alternate feeling and thinking. (1 = Strongly Disagree, 5 = Strongly Agree)",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="Rate: My decisions improve when I balance heart and mind. (1 = Strongly Disagree, 5 = Strongly Agree)",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="Rate: I tend to favor one over the other, causing imbalance. (1 = Strongly Disagree, 5 = Strongly Agree)",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
]

PAST_LIFE_VIBES_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="When teaching or guiding others, what do you feel most strongly?",
        answer_type="single_choice",
        options=[
            "Instant familiarity and ease",
            "Nervous anticipation that fades quickly",
            "Curiosity about why it feels \"right\"",
            "Neutral; it feels like any other task",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Some activities feel like \"second nature.\" Which describe you? (Select up to 2)",
        answer_type="multiple_choice",
        options=[
            "Storytelling or mentoring",
            "Healing work (energy, body, mind)",
            "Leading group rituals or ceremonies",
            "Researching ancient cultures or histories",
        ],
        max_selections=2,
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="Have you ever experienced a \"déjà vu\" moment that felt spiritually significant?",
        answer_type="single_choice",
        options=["Frequently", "Occasionally", "Rarely", "Never"],
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="When you learn a new skill, do you:",
        answer_type="single_choice",
        options=[
            "Master it unusually quickly",
            "Feel drawn to teach it to others",
            "Experience vivid mental images or memories while learning",
            "None of the above",
        ],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="Do you feel called to preserve or revive any traditions or knowledge?",
        answer_type="single_choice",
        options=["Yes", "No"],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="What tradition or knowledge?",
        answer_type="text",
        options=None,
        show_when=ShowWhen(question_id=5, value="Yes"),
        required=False,
    ),
]

KARMIC_LESSONS_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="I often hold back my opinion to keep the peace.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Expressing my needs feels:",
        answer_type="single_choice",
        options=[
            "Easy and natural",
            "Occasionally awkward",
            "Mostly difficult",
            "Nearly impossible",
        ],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="When someone oversteps my boundaries, I typically:",
        answer_type="single_choice",
        options=[
            "Speak up immediately",
            "Feel upset but say nothing",
            "Distance myself later",
            "Confront them later when calm",
        ],
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="Which resonates most?",
        answer_type="single_choice",
        options=[
            "I'm learning to say \"no\" without guilt.",
            "I'm learning to assert needs gently.",
            "I'm learning to recognize my right to speak up.",
        ],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="Do you have a recurring childhood memory where you felt unheard?",
        answer_type="single_choice",
        options=["Yes", "No"],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="Briefly describe (optional):",
        answer_type="text",
        options=None,
        show_when=ShowWhen(question_id=5, value="Yes"),
        required=False,
    ),
]

INNER_CHILD_DIALOGUE_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="When you feel anxious or sad, do you:",
        answer_type="single_choice",
        options=[
            "Comfort yourself with kind words",
            "Distract yourself until it passes",
            "Criticize yourself (\"snap out of it\")",
            "Seek support from someone else",
        ],
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="Do you remember specific childhood hurts you've never resolved?",
        answer_type="single_choice",
        options=["Yes", "No"],
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="List one or two (optional):",
        answer_type="text",
        options=None,
        show_when=ShowWhen(question_id=2, value="Yes"),
        required=False,
    ),
    QuestionOut(
        id=4,
        prompt="How often do you check in with your inner child's feelings?",
        answer_type="single_choice",
        options=["Daily", "Weekly", "Monthly", "Rarely"],
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="If you could speak to your younger self, what tone would you use?",
        answer_type="single_choice",
        options=[
            "Gentle reassurance",
            "Firm guidance",
            "Friendly peer-to-peer",
            "I'm not sure",
        ],
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="Which feels most healing?",
        answer_type="single_choice",
        options=[
            "Saying \"I love you\" to yourself",
            "Telling yourself \"I am safe\"",
            "Reminding yourself \"I matter\"",
            "Visualizing a protective space",
        ],
        required=True,
    ),
]

BIG_FIVE_QUESTIONS: list[QuestionOut] = [
    QuestionOut(
        id=1,
        prompt="I enjoy trying new and unconventional ideas.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=2,
        prompt="I have a rich imagination.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=3,
        prompt="I keep my belongings tidy and organized.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=4,
        prompt="I follow through on my plans.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=5,
        prompt="I feel comfortable around people.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=6,
        prompt="I start conversations easily.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=7,
        prompt="I sympathize with others' feelings.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=8,
        prompt="I take time out for others.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=9,
        prompt="I get stressed out easily.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
    QuestionOut(
        id=10,
        prompt="I sometimes feel blue.",
        answer_type="slider",
        options=None,
        slider_min=1,
        slider_max=5,
        required=True,
    ),
]

QUESTIONS_BY_TEST_ID: dict[int, list[QuestionOut]] = {
    3: STARSEED_ORIGINS_QUESTIONS,
    7: MBTI_TYPE_QUESTIONS,
    8: SHADOW_WORK_LENS_QUESTIONS,
    9: BIG_FIVE_QUESTIONS,
    10: CORE_VALUES_SORT_QUESTIONS,
    11: COGNITIVE_STYLE_QUESTIONS,
    12: MIND_MIRROR_QUESTIONS,
    13: CHAKRA_ALIGNMENT_SCAN_QUESTIONS,
    14: ENERGY_ARCHETYPE_QUESTIONS,
    15: EMOTIONAL_REGULATION_TYPE_QUESTIONS,
    16: STRESS_BALANCE_INDEX_QUESTIONS,
    17: SOMATIC_CONNECTION_QUESTIONS,
    18: ENERGY_SYNTHESIS_QUESTIONS,
    21: PAST_LIFE_VIBES_QUESTIONS,
    22: KARMIC_LESSONS_QUESTIONS,
    23: INNER_CHILD_DIALOGUE_QUESTIONS,
}
